#pragma once
#include <cstdint>
#include <Unknwn.h>

struct TDriverParams
{
	char DriverName[51];
	int32_t DriverFlags;
	char ShortCut;//this is the desired shortcut for this plugin if you are using it in menus or actions.Key modifiers depend on the host application
};



struct __declspec(uuid("368EC636-02D4-4648-8DB9-49BC65F55E2A")) IPlayBoxOut :public IUnknown
{
	//retunrs 0 if inited ;1 if inited and activated;-1 on error
	virtual HRESULT _stdcall Init(void** DriverData) = 0;

	//Done is called when plugin must finalize his work
	virtual HRESULT _stdcall Done(void* DriverData) = 0;

	//GetParams is used to acquire more details about the plugin
	virtual HRESULT _stdcall GetParams(TDriverParams* Params) = 0;

	//Setup for current instance
	virtual HRESULT _stdcall Config(void * DriverData) = 0;


	//Executes command string that was previously generated by NewCommand function
//the format of the string has to be:
//[Command title];[Command data]
	virtual HRESULT _stdcall Execute(const char * Command,void * DriverData) = 0;


	//Call this to acquire command string which can be executed or edited later.Buffer must be at least 16K
//returns 0 on success ,-1 on error or cancel
//the retuned string has following format :
//[Command title];[Command time offset];[Command data];[Visual duration];[Command flags]
//command title - string that can be used to display this command.
//command time offset - time offset (in msecs) which this command has to be executed.Host application will decide to use (and implement) this or not
//command data - data string for the command
//Visual duration-float number that can be used to show the commands duration(whole number is seconds)
//
	virtual HRESULT _stdcall NewCommand(char** Command, void * DriverData) = 0;


	//Edit cmd string previously returned by NewCommand.Buffer must be at least 16K
//returns 0 on success ;-1 on error or cancel
	virtual HRESULT _stdcall EditCommand(char** Command, void* DriverData) = 0;

	//Call this to activate plugin. 0 on succes
	virtual HRESULT _stdcall Activate(void * DriverData) = 0;

	//Call this to deactivate plugin
	virtual HRESULT _stdcall Deactivate(void * DriverData) = 0;

	//Call this function if Execute command returns -1.This function will return error message.
	virtual HRESULT _stdcall GetLastErrorString(char* Text, DWORD* pSz) = 0;

	virtual HRESULT _stdcall About() = 0;
};




